
name: React App in container

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: make build
  
  start:
    runs-on: self-hosted
    needs: build
    steps:
    - uses: actions/checkout@v3
    - name: Run the Docker container
      run: make run
    - name: Start the Docker container
      run: make start
